### ISSUE TITLE
Put template inside normal brackets for better IDE support

### ISSUE THREAD

**Issue by fabian-michael** [mistlog/svelte-draft#2]
I am using PHPStorm (IntelliJ) and I got an error with the template syntax (statement expected). Putting my template inside normal brackets fixed that.

**Comment by mistlog** [comment]
Would you like to give an example on "Putting my template inside normal brackets".

The problem I know is that we have to add ";" between adjacent JSX such as :

```javascript
<div>hi</div>;
<div>hello</div>
```

I'm not sure if it's related to your question, so an example may be helpful.

**Comment by fabian-michael** [comment]
Oh seems that I messed up something and it was something else that caused the error. Maybe it was what you mentioned. My bad
