### ISSUE TITLE
Webpack support

### ISSUE THREAD

**Issue by fabian-michael** [mistlog/svelte-draft#5]
Hi, is there already a loader/plugin for webpack?

**Comment by mistlog** [comment]
Currently there is no loader/plugin for webpack.

I'm not familiar with webpack, if you need it, I can implement one, but it takes some time for me to learn it. Or if you are interested in it, I think the [rollup](https://github.com/mistlog/rollup-plugin-svelte-draft) version can be a reference.

**Comment by fabian-michael** [comment]
It's quite easy and I could try but unfortunately I haven't that much time. I am in an apprenticeship as an IT specialist (web development) and also involved in our customer projects. Maybe I could do it as an educational project by my own.

**Comment by mistlog** [comment]
I accepted the invitation of [svelte-draft-loader](https://github.com/Mycl95/svelte-draft-loader), thanks!

So what does `educational project` mean? Anyway, I'm going to learn webpack in order to join the discussion of the loader implementation later.

**Comment by fabian-michael** [comment]
That means just that I do this for learning purposes as part of my apprenticeship during my working hours haha 😄

**Comment by mistlog** [comment]
Great, feel free to ask any questions!

**Comment by fabian-michael** [comment]
Should it really be able to transpile pure typedraft (the part with `if (id.endsWith('.js.tsx') || id.endsWith('.ts'))` ) ?

I would do that in another plugin or loader. So it has clear separation of concerns.

**Comment by mistlog** [comment]
Yes, it works, svelte-draft is built upon typedraft.
However, I think the suggestion is good, we can have standalone plugin or loader for typedraft!

**Comment by fabian-michael** [comment]
I can't publish on npmjs right now because I can't verify my email address. I get a service unavailable error.

**Comment by mistlog** [comment]
If you are using computer in your company, the npm registry may point to private one. 
`npm publish` works only if `npm config get registry` returns `https://registry.npmjs.com/`.

**Comment by fabian-michael** [comment]
I am in home office (due to corona virus) and in my home network. But it fails at verifying my email address. And I can't publish without verifying it.

**Comment by mistlog** [comment]
> fails at verifying my email

when you create npm account or run command `npm publish`?

**Comment by fabian-michael** [comment]
Creating my account. 
When I open the verification link in the email I get a service unavailable error. 
And when trying to publish it says I have to verify my email address first.

**Comment by mistlog** [comment]
Yes, you have to create the account first.

Before you run `npm publish`, `npm login` is also needed.

**Comment by mistlog** [comment]
I remembered that when I create my account, after verifying it,  "please verify your email..." still exists on the site, but I just ignored it and `npm login`, `npm publish` works fine.

**Comment by fabian-michael** [comment]
It worked now. It's online! 😄

**Comment by mistlog** [comment]
Great! Thanks for spending time on it!
I'm going to have a try(loader and template) and add them to docs.

**Comment by mistlog** [comment]
:) it works well, and I added it to [svelte-draft-tutorial](https://github.com/mistlog/svelte-draft-tutorial) as well!
