### ISSUE TITLE
Component State management

### ISSUE THREAD

**Issue by sanitherayil** [mistlog/svelte-draft#7]
How we can get component state.. In svelte we can use bind:value which is a bi directional binding. Please help to get component state out side ...

**Comment by mistlog** [comment]
The equivalent of bind:value in svelte-draft is bindValue, for example:  [6-binding/numeric-inputs](https://github.com/mistlog/svelte-draft-tutorial/blob/ccbc86943b5be57beeee5ec0e01f492f06a26001/src/examples/6-binding/numeric-inputs/App.tsx#L7)
